name: build
on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setting Java17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Setting Gradle
        uses: gradle/wrapper-validation-action@v1
      - name: Set the gradlew file permissions
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: Mod
          path: build/libs/