name: build
on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 准备存储库
        uses: actions/checkout@v3
      - name: 设置JDK17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: 设置Gradle
        uses: gradle/wrapper-validation-action@v1
      - name: 设置gradlew文件权限
        run: chmod +x ./gradlew
      - name: 构建
        run: ./gradlew build
      - name: 上传构建资源
        uses: actions/upload-artifact@v1
        with:
          name: Mod
          path: build/libs/